# Generated by Django 5.0 on 2023-12-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainScroll1Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main-scroll')),
                ('title', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=250)),
                ('discount', models.PositiveSmallIntegerField()),
                ('price', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'scroll1',
                'verbose_name_plural': 'scrolls1',
            },
        ),
    ]
